'use client';
import { useState } from 'react';
import { ArrowRight, ExternalLink, Loader2, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
type Result = { finalUrl: string; hops: { url: string; status: number; location?: string }[]; truncated: boolean };
export function LinkExpander() { const [url, setUrl] = useState(''); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function trace() { setLoading(true); setError(''); setResult(null); try { const response = await fetch('/api/tools/link-expander', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to trace this URL.'); } finally { setLoading(false); } }
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-2xl"><ShieldCheck className="h-6 w-6 text-primary" /> Link Expander &amp; Hop Tracer</CardTitle><CardDescription>Reveal redirect chains safely. The destination page is never loaded in your browser.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex gap-2"><Input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/short-link" aria-label="URL to expand" onKeyDown={(event) => { if (event.key === 'Enter') void trace(); }} /><Button onClick={() => void trace()} disabled={loading || !url.trim()}>{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <>Trace <ArrowRight className="ml-2 h-4 w-4" /></>}</Button></div>{error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{result && <div className="space-y-3"><div className="rounded-md bg-muted p-4"><p className="text-sm text-muted-foreground">Final destination</p><a className="break-all font-medium text-primary hover:underline" href={result.finalUrl} target="_blank" rel="noreferrer">{result.finalUrl} <ExternalLink className="inline h-4 w-4" /></a></div><ol className="space-y-2 text-sm">{result.hops.map((hop, index) => <li key={`${hop.url}-${index}`} className="break-all rounded border p-3"><span className="mr-2 rounded bg-muted px-2 py-1 font-mono">{hop.status}</span>{hop.url}{hop.location && <span className="text-muted-foreground"> → {hop.location}</span>}</li>)}</ol>{result.truncated && <p className="text-sm text-muted-foreground">Trace stopped after 10 redirects.</p>}</div>}</CardContent></Card>; }
